// Audio PLL: 50 MHz -> ~12.288 MHz for WM8731 MCLK (256fs @ 48 kHz)
// Structure mirrors vga_pll.v generated by Quartus MegaWizard

`timescale 1 ps / 1 ps
module audio_pll (
    input  wire  refclk,
    input  wire  rst,
    output wire  outclk_0,
    output wire  locked
);

    audio_pll_0002 audio_pll_inst (
        .refclk   (refclk),
        .rst      (rst),
        .outclk_0 (outclk_0),
        .locked   (locked)
    );

endmodule
